services:
  web:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      SUPABASE_URL: https://aplicativos-db-phm2-supabase.xqzrhl.easypanel.host
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      TZ: America/Sao_Paulo
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
