# ====================================
# Docker Compose para EasyPanel
# ====================================

services:
  # Aplicação Principal
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL:-https://app-phm-psj-db-phm2-supabase.xqzrhl.easypanel.host}
      - 
